version: "3.3"
services:
  springboot-app:
    container_name: spring_app_backend
    image: lakshmihegdeiiitb/gift_spring
    ports:
      - 9088:9087
    volumes:
      - /home/lakshmi/Desktop/DB:/var/lib/mysql
    restart: always


  mysql_service:
    container_name: mysqldatabase
    image: mysql:8.0
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: GiftDB
      MYSQL_ROOT_PASSWORD : password
      MYSQL_PASSWORD: password
      MYSQL_USER: lakshmi