---
- name: Deploy spring and sql containers
  hosts: all
  tasks:
    - name: Delete all running containers
      shell: " docker rm -f $(docker ps -a -q) " 
      
    - name: Delete all images
      shell: " docker rmi -f $(docker images -q) "
             
    - name: Copy Docker compose file to destination
      copy:
          src: ../docker-compose.yml
          dest: .
          
    - name: Execute docker compose
      docker_compose:
       project_src: .
       state: present
      register: dockercompose
     
    - name: Container info
      debug:
        var: dockercompose
