---
- name: Deploy spring and sql containers
  hosts: all
  tasks:
    - name: Remove all images and containers
      command: docker rm $(docker ps -a -q) 
      command: docker rmi -f $(docker images -q)
      command: docker kill $(docker ps -q)
    - name: Copy Docker compose file to destination
        copy:
          src: ../
          dest: .
    - name: Docker compose up
        docker_compose:
          project_src: .
          state: present
        register: __docker_compose
    - name: debug
      debug:
        var: __docker_compose

