---
- name: Deploy spring and sql containers
  hosts: all
  tasks:
    - name: Remove all images and containers
      shell:
        " docker rm $(docker ps -a -q) "
        " docker rmi -f $(docker images -q) "
        " docker kill $(docker ps -q) "
    - name: Copy Docker compose file to destination
        copy:
          src: ../
          dest: .
    - name: Docker compose up
        docker_compose:
          project_src: .
          state: present
        register: __docker_compose
    - name: debug
      debug:
        var: __docker_compose

